default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: dbuser
  password: dbpass
  host: localhost

development:
  <<: *default
  database: tasklist_development

production:
  <<: *default
  database: tasklist_production
  username: tasklist
  password: <%= ENV['TASKLIST_DATABASE_PASSWORD'] %>